### PR TITLE
feat: new account page, new nav section, smaller homepage

### LINKED ISSUE #54: Homepage Update
## Context

1. The https://www.designsafe-ci.org/user-guide/ index has good authentication information, and an overview.
2. The https://www.designsafe-ci.org/help/getting-started/ links to https://www.designsafe-ci.org/user-guide/.

## Problem

1. The authentication has no heading. ~~The overview (under "NAVIGATING THE USER GUIDE") is out of date.~~
2. The User Guide does not clearly advertise itself as a Getting Started page.

## Ideas

Move authentication information to its own page and show in navigation.

1. [Polish] homepage overview and remove "NAVIGATING …" title.
2. Point "Getting Started" to authentication page.

### PR DESCRIPTION
**Pull request by wesleyboar**
## Overview

Update homepage. Move account access to new page. New top nav section.

## Status

> [!IMPORTANT]
> Pending stakeholder review ([internal, private](https://tacc-team.slack.com/archives/C05H55XDAMR/p1726526642998519)).

## Related

- closes #54
- similar to #55

## Changes

- **removed** date last updated (can be found on GitHub)
- **moved** account access to its own page
- **changed** "Tools & Apps" to "Tools and Apps" (to match nav)
- **added** new nav section "DesignSafe Essentials" (like [TACC Docs](https://docs.tacc.utexas.edu/))

## Testing

1. Open:
    - (if deployed to dev) https://designsafeci-dev.tacc.utexas.edu/user-guide/
    - (local) http://0.0.0.0:8000/user-guide/
2. See:
    - new nav section "DesignSafe Essentials"
    - new content "DesignSafe Essentials: …"
3. Verify **Documentation Outline** is highlighted (as current).
4. Click **Account Access**.

## UI

<details open><summary>

### After [enhance: rework as Getting Started & Account Help](https://github.com/DesignSafe-CI/DS-User-Guide/pull/67/commits/5eece53)

</summary>

#### Getting Started

| before | after |
| - | - |
| index - old | index - new |

#### Account Help

| before | after |
| - | - |
| account - old | account - new |
| (lost) | |

</details>

<details><summary>

### Before [enhance: rework as Getting Started & Account Help](https://github.com/DesignSafe-CI/DS-User-Guide/pull/67/commits/5eece53)

</summary>

#### Homepage & Nav

| before | after |
| - | - |
| before homepage change | after homepage change |

#### Account Access

| before | after |
| - | - |
| before homepage change | account access |

</details>

### CODE REVIEW

**Comment by wesleyboar** [comment]
@silviamazzoni, Please take a look at this new index page and top section. It's changed since last time. At least during today, you can preview it on https://designsafeci-dev.tacc.utexas.edu/user-guide/.

**Comment by silviamazzoni** [comment]
Wes, I am happy to meet. The main note is that the section titles, such as DesignSafe Essentials, Data Depot, Tools and Apps, etc should be aligned left so that we know they are not a link. a different format could work. 
The difference between Data Depot and Overview is so small, and yet Overview has a link.
Why does Overview in Simulation Applications actually have sections that don't seem like an overview.... And why do DS Essentials and  Tools and Apps not have an Overview?

**Comment by silviamazzoni** [comment]
also, clicking on a section in the Use Cases overview should open up the corresponding item in the nav...

**Comment by silviamazzoni** [comment]
Also, there is still too much empty space at the top, both in the nav and in the page.

**Comment by silviamazzoni** [comment]
also, when I clikc on an item in the nav, it scrolls the left nav up so that that item is that at the top... very disturbing and makes it hard to visualize the full section.

**Comment by wesleyboar** [comment]
Understood.

> The difference between Data Depot and Overview is so small, and yet Overview has a link.

Known issue; in progress:
- #75

Other feedback seems external to the problem being solved (which is adding "Getting Started" and restoring lost content to get help for account).

---

<details><summary>I gather it for reference, and give answers.</summary>

> Section titles, such as DesignSafe Essentials, Data Depot, Tools and Apps, etc should be aligned left […]

This is a reasonable opinion. Although, in one sense, they are aligned left because the text is aligned left; the arrow is outside the alignment. Independent of this content-focused PR, feel free to continue to remind me about this element. (I forget what designer's feedback was when last I mentioned it.)

> Why does Overview in Simulation Applications actually have sections that don't seem like an overview....

Uncertain. I am unfamiliar with pre-existing content.

> And why do DS Essentials and Tools and Apps not have an Overview?

Uncertain. I presume "Overview" pages are new additions and have not been viewed as a standard per section.

**Update:**

> Also, there is still too much empty space at the top, both in the nav and in the page.

Design concern. Seems irrelevant to the problem this PR solves. Feel free to [open a new issue](https://github.com/DesignSafe-CI/DS-User-Guide/issues/new).

> [When I click] on an item in the nav, it scrolls the left nav up so that that item is that at the top... very disturbing and makes it hard to visualize the full section.

Aye, it does. Sometimes it can not scroll item to top, and instead scrolls nav up as far as it can, with relevant item appearing in the middle of the nav. I am continuously aware of this issue, and hope it is fixed on its own after https://github.com/TACC/TACC-Docs/issues/53.

</details>

**Comment by wesleyboar** [comment]
<details><summary>I updated <a href="https://github.com/DesignSafe-CI/DS-User-Guide/pull/67#issuecomment-2353863937">my original response</a> with answers to feedback I missed.</summary>

<br>

> Also, there is still too much empty space at the top, both in the nav and in the page.

Design concern. Seems irrelevant to the problem this PR solves. Feel free to [open a new issue](https://github.com/DesignSafe-CI/DS-User-Guide/issues/new).

> [When I click] on an item in the nav, it scrolls the left nav up so that that item is that at the top... very disturbing and makes it hard to visualize the full section.

Aye, it does. Sometimes it can not scroll item to top, and instead scrolls nav up as far as it can, with relevant item appearing in the middle of the nav. I am continuously aware of this issue, and hope it is fixed on its own after https://github.com/TACC/TACC-Docs/issues/53.

</details>

**Comment by wesleyboar** [comment]
Merging based on informal approval.

I made these changes under @heddabedda's direction.

I got review from @silviamazzoni (colleague), @heddabedda's (new author), and one project stakeholder. Original content is basically as is, just moved around. I will request a second stakeholder to scan it after deploy.

**Pull request merged**
