### PR TITLE
use cases: broke down into separate files and fixed some headers that…

### PR DESCRIPTION
**Pull request by silviamazzoni**
## Overview

Broke down Use Cases into separate files and fixed some headers that had not been updated.

## Testing

We do need to check the links from the nav because they want to connect to an anchor, not  a file, which is how they are set up now.

## UI

<details open><summary>since TACC-Docs <strong>v0.10</strong></summary>

https://github.com/user-attachments/assets/8434be01-9e57-4f45-802a-5ede69007492

https://github.com/user-attachments/assets/fb1ad5c6-a1a2-4285-8ad1-2d9ace5944d2

</details>
<details><summary>using TACC-Docs <strong>v0.8</strong></summary>

sample document header

https://github.com/user-attachments/assets/0424e5ed-fd37-4ae7-91a6-fa563a4ee86e

detailed nav is automatically open

https://github.com/user-attachments/assets/33460a86-5a78-42d3-808b-d88ff90e9485

</details>

<sub>edited by @wesleyboar (organized and added visuals)</sub>

### CODE REVIEW

**Comment by wesleyboar** [comment]
There are navigation bugs when using flat navigation. Reported in [DES-3045](https://tacc-main.atlassian.net/browse/DES-3045). Expect solution via TACC-Docs update.

**Comment by wesleyboar** [comment]
> [!TIP]
> If testing [via Docker](https://github.com/DesignSafe-CI/DS-User-Guide#b-via-docker), there are **no** navigation bugs introduced by this change.

> [!CAUTION]
> If testing [via Python](https://github.com/DesignSafe-CI/DS-User-Guide#a-via-python), **several** navigation bugs are introduced by this change.

**Review by wesleyboar — COMMENTED** [review]
Sort of blocked by #66 because most contributors will not test via Docker.

- https://github.com/DesignSafe-CI/DS-User-Guide/issues/66

If you are okay with the nav bugs for Python-based testing, then I'll merge this.

Otherwise, please wait until I have time to solve #66.

**Comment by silviamazzoni** [comment]
Wes, do you have an update on this?

**Comment by wesleyboar** [comment]
No update. Same status as it was in https://github.com/DesignSafe-CI/DS-User-Guide/pull/63#pullrequestreview-2202873603. I've been taken by DesignSafe website work and another project. Still an excellent PR. I don't mind it staying open, let's me know what is still waiting on me.

If you are okay with the nav bugs for Python-based testing, please tell and reopen so I can merge. Otherwise, this would wait until have time to solve https://github.com/DesignSafe-CI/DS-User-Guide/issues/66.

**Comment by silviamazzoni** [comment]
The nav bugs are are only on my testing end, correct?
And they are just style bugs? 
The public version of the docs would be perfect and have the separated docs, correct?
If I want to replicate the site locally exactly, I'd have to use the docker, correct?
If so, yes, please accept this PR.

**Comment by wesleyboar** [comment]
Yes x4. Merged.

**Pull request merged**
