### PR TITLE
feat: des-2792 migrate OpenSees app desc from portal

### PR DESCRIPTION
**Pull request by wesleyboar**
## Overview

Migrate [DS Workspace: OpenSees](https://www.designsafe-ci.org/rw/workspace/#!/OpenSees::Simulation) instructions to [DS User Guide: OpenSees](https://www.designsafe-ci.org/user-guide/tools/simulation/opensees/).

<details><summary>Background</summary>

The [DS Workspace](https://www.designsafe-ci.org/rw/workspace/) is being redesigned. Add descriptions have been moved, but not yet OpenSees' instructions within its app description.

</details>

## Related

* [DES-2792](https://tacc-main.atlassian.net/browse/DES-2792)

## Changes

* **added** `…/openseesDesignSafeQuickStart.md`
* **added** link in `…/opensees.md` to new Quick Start doc

## Testing

1. Run application.
2. Open http://0.0.0.0:8000/user-guide/tools/simulation/opensees/opensees/.
3. Under "OpenSees on DesignSafe", find
    > Abbreviated User Guide: [OpenSees On DesignSafe Quick Start](http://0.0.0.0:8000/user-guide/tools/simulation/opensees/openseesDesignSafeQuickStart/)
4. Click link.
5. Compare document to documentation at https://www.designsafe-ci.org/rw/workspace/#!/OpenSees::Simulation.

## UI

| OpenSees on DesignSafe | OpenSees on DesignSafe: Quick Start |
| - | - |
| new link | ds os qs 1 |
| | ds os qs 2 |
| | ds os qs 3  |

## Notes

> [!NOTE]
> The `<details>` element will be available **after** #1, so we can do:
>
> <details><summary><h4>Instructions</h4></summary>
> 1. … 2. … 3. …
> </details>

### CODE REVIEW

**Comment by wesleyboar** [comment]
@silviamazzoni, I will add you as reviewer when admin approves. For now, feel free to review and comment if able. If you would rather create your own PR, go for it. I could merge this in, without linking to it, then link to it when you are satisfied.

**Comment by silviamazzoni** [comment]
Wes, looking at the image on the right, I don't see the OpenSees opened up on the left.  I recommend you add it as the very first subsection to OpenSees on DesignSafe. thank you for doing the conversion. i am guessing that once you receive approval, go ahead and merge it, and then I can from that.
thank you

**Review by silviamazzoni — COMMENTED** [review]
maybe: OpenSees-on-DesignSafe Quick Start

**Comment by wesleyboar** [comment]
@silviamazzoni, update:
1. "Quick Start" now included (not linked) as "OpenSees-on-DesignSafe Quick Start".
    <sub>Heading depth updated accordingly.</sub>
2. Lists that had used "A. B. C." now do again.
3. Left comments about when and how we can use `<details>`.
   <sub>(basically: not yet, but soon, via `/// details | Instructions`)</sub>

**Comment by wesleyboar** [comment]
You're welcome to make further updates.

**Comment by silviamazzoni** [comment]
yes, once your work is fully merged I will update my end.

**Pull request merged**
